- name: create kubectl directory
  file:
    path: "~/.kube"
    state: directory

- name: copy manifests files
  template: 
    src: "{{ item }}"
    dest: "/etc/kubernetes/manifests/{{ item | basename | regex_replace('.j2','') }}"
    mode: +x
  with_fileglob:
    - ../templates/manifests/*.j2

- name: copy cert scripts
  template:
    src: "Scripts/createCA.sh.j2"
    dest: "/etc/kubernetes/pki/createCA.sh"
    mode: +x

- name: copy proxy cert scripts
  template:
    src: "Scripts/createProxyCa.sh.j2"
    dest: "/etc/kubernetes/pki/createProxyCa.sh"
    mode: +x
 
- name: create haproxy directory
  file:
    path: "{{ haproxy.dir }}"
    state: directory

- name: create keepalived directory
  file:
    path: "{{ keepalived.dir }}"
    state: directory

- name: copy haproxy cfg file
  template:
    src: "config/haproxy.cfg.j2"
    dest: "{{ haproxy.dir }}/haproxy.cfg"

- name: copy keepalived cfg file
  template:
    src: "config/keepalived.conf.j2"
    dest: "{{ keepalived.dir }}/keepalived.conf"

- name: copy keepalived check scripts
  template:
    src: "config/check_apiserver.sh.j2"
    dest: "{{ keepalived.dir }}/check_apiserver.sh"
    mode: +x

- name: install cfssl
  get_url:
    url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
    dest: /usr/local/bin/cfssl
    mode: +x

- name: install cfssljson
  get_url:
    url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
    dest: /usr/local/bin/cfssljson
    mode: +x

- name: install cfssl-cert-info
  get_url:
    url: https://pkg.cfssl.org/R1.2/cfssl-certinfo_linux-amd64
    dest: /usr/local/bin/cfssl-certinfo
    mode: +x

- name: generate certs and keys
  command: chdir=../etc/kubernetes/pki ./createCA.sh

- name: generate proxy certs and keys
  command: chdir=../etc/kubernetes/pki ./createProxyCa.sh

- name: copy stand-alone kubelet config
  copy:
    src: "kubelet_cfg/10-kubeadm.conf.1"
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
    mode: +x

- name: start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: true
    daemon_reload: yes

- name: copy kubectl config file
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "~/.kube/config"

