- pause:
    minutes: 1

- name: create clusterrolebinding
  local_action: shell kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap
  run_once: true

- name: copy boot-strap kubelet config
  copy:
    src: "kubelet_cfg/10-kubeadm.conf.2"
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
    mode: +x

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    
- pause:
    seconds: 30

- name: approve csr
  shell: "kubectl get csr | awk 'NR>=2{print $1}' | xargs kubectl certificate approve"
  run_once: true
  delegate_to: "{{ master1 }}"

- name: copy full kubelet config
  copy:
    src: "kubelet_cfg/10-kubeadm.conf.3"
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
    mode: +x
  notify: 
  - restart kubelet
  - short pause
  - label master



