apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --name=etcd2
    - --advertise-client-urls=http://192.168.56.102:2379
    - --initial-advertise-peer-urls=http://192.168.56.102:2380
    - --listen-peer-urls=http://192.168.56.102:2380
    - --listen-client-urls=http://127.0.0.1:2379,http://192.168.56.102:2379
    - --data-dir=/var/lib/etcd
    - --initial-cluster=etcd1=http://192.168.56.101:2380,etcd2=http://192.168.56.102:2380,etcd3=http://192.168.56.103:2380
    - --initial-cluster-token=etcd-cluster
    - --initial-cluster-state=new
    image: gcr.io/google_containers/etcd-amd64:3.1.11
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 192.168.56.102
        path: /health
        port: 2379
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd
status: {}
