- name: login into private registry
  docker_login:
    registry: "{{ docker_private_registry }}"
    username: "{{ docker_private_registry_user }}"
    password: "{{ docker_private_registry_password }}"
    reauthorize: yes
  ignore_errors: yes

- name: copy docker images scripts
  copy:
    src: "Scripts/pull_images.sh"
    dest: "{{ images_pull_scripts_dir }}"
    mode: +x

- name: pull images
  shell: "{{ images_pull_scripts_dir }}/pull_images.sh"

- name: install kubernetes rpm pkg
  shell: yum localinstall -y {{ rpm_dir }}/*.rpm

- name: create pki directory
  file:
    path: "/etc/kubernetes/pki"
    state: directory

- name: create manifests directory
  file:
    path: "/etc/kubernetes/manifests"
    state: directory

- name: create etcd storage dir
  file:
    path: "{{ etcd_dir }}"
    state: directory
  when: etcd_volume_mount

- name: create etcd soft link
  shell: ln -s "{{ etcd_dir }}" /var/lib
  when: etcd_volume_mount
  ignore_errors: yes
