- name: login into private registry
  docker_login:
    registry: "{{ docker_private_registry }}"
    username: "{{ docker_private_registry_user }}"
    password: "{{ docker_private_registry_password }}"
    reauthorize: yes
  ignore_errors: yes

- name: copy docker images scripts
  copy:
    src: "Scripts/pull_images.sh"
    dest: "{{ images_pull_scripts_dir }}"
    mode: +x

- name: pull images
  shell: "{{ images_pull_scripts_dir }}/pull_images.sh"

- name: install kubernetes rpm pkg
  shell: yum localinstall -y {{ rpm_dir }}/*.rpm

- name: create pki directory
  file:
    path: "/etc/kubernetes/pki"
    state: directory

- name: create manifests directory
  file:
    path: "/etc/kubernetes/manifests"
    state: directory

- name: copy manifests files
  copy: 
    src: "{{ item }}"
    dest: "/etc/kubernetes/manifests"
    mode: +x
  with_fileglob:
    - manifests/*

- name: copy certs
  copy:

- name: copy config
  copy:

- name: copy stand-alone kubelet config
  copy:
    src: "kubelet_cfg/10-kubeadm.conf.1"
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
    mode: +x
    backup: yes

- name: start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: true
    daemon_reload: yes

- pause:
    minutes: 1 

- name: copy boot-strap kubelet config
  copy:
    src: "kubelet_cfg/10-kubeadm.conf.2"
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
    mode: +x

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    
- pause:
    minutes: 1

- name: approve csr
  shell: /etc/ansible/roles/kube/files/Scripts/approve_csr.sh

- name: copy full kubelet config
  copy:
    src: "kubelet_cfg/10-kubeadm.conf.3"
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
    mode: +x
  notify: 
  - restart kubelet

